### ISSUE TITLE
Empty Files Encountered

### ISSUE THREAD

**Issue by jcrawford** [ideaconnect/idct-sftp-client#3]
I have a CLI application which is used to download distributor inventory files and then download all valid product image files.  The issue I am having is that the download method is returning as if it was successful however the files are Zero bytes in size.

I am not sure if the connection is timing out or what the cause may be but it is downloading over 2000 jpg images.  It is not erroring out on the same files either as when I encountered the issue with an image if I stop and restart my process it will download the image just fine.

I have traced it to the download method call because it is in-fact creating the local file and returning as if it was successful.  Here was my original code which was failing.

``` php
    try {
        $fetched = @$this->_ssh->download(
            'Images/' . trim($itemno . '.jpg'),
            self::PRODUCT_IMAGE_SOURCES . $product_image
        );
    } catch (\Exception $e) {
        // image could not be found on remote server.
        return false;
    }
```

Here is my code with some error handling in place, which doesn't seem to fully work at this time either.

``` php
    $fetched = false;
    while($fetched == false && $attempts < 3 ) {
        try {
            $result = @$this->_ssh->download(
                'Images/' . trim($itemno . '.jpg'),
                self::PRODUCT_IMAGE_SOURCES . $product_image
            );
            if(file_exists(self::PRODUCT_IMAGE_SOURCES . $product_image) && filesize(self::PRODUCT_IMAGE_SOURCES . $product_image) > 0) $fetched = true;
            else {
                $this->sftpReconnect();
                $attempts++;
                continue;
            }
        } catch (\Exception $e) {
            // image could not be found on remote server.
            return false;
        }
        $attempts++;
    }
```

I am thinking there is a deeper issue internally in the SftpClient because it is returning as if it was successful when it either didn't download the contents or failed to write the contents to the local file.

I will be happy to share any more code that you feel may be required.

**Comment by ideaconnect** [comment]
Added an option to strictly verify - can be enabled using `enableFileSizeVerification()`
