### ISSUE TITLE
Segmentation Fault listing directory

### ISSUE THREAD

**Issue by jcrawford** [ideaconnect/idct-sftp-client#5]
I am trying to list a directory and the SftpClient is throwing a segfault when readdir() is encountered, this is the area of the code where the issue exists.

https://github.com/ideaconnect/idct-sftp-client/blob/1d055e688a0bf3073ca417157ac36f7b19c5b5ad/src/SftpClient.php#L475

Appears it may be a bug in PHP or the SSH2 library, just thought I would relay the issue to you.

``` php
<?php
$remote_files = $this->_ssh->getFileList('Images/');
```

The above code is all I am doing with the SftpClient code to get the following segfault

``` text
jcrawford@Josephs-Mac-mini:~/TraderTools (dev *) # ./traders.php --action=all
/usr/bin/php: line 4: 34411 Segmentation fault: 11  $ZCE_PREFIX/bin/php.bin -c $ZCE_PREFIX/etc/php.ini "$@"
```

**Comment by ideaconnect** [comment]
@jcrawford thank you for sharing the issues which you have encountered. I shall review them and do my best to find out what are the problems as soon as possible.

**Comment by Spaarw** [comment]
I got the same issue..

**Comment by ideaconnect** [comment]
There is PHP SSH2 bug:
https://bugs.php.net/bug.php?id=71376

Made a workaround in the latest commits:
https://github.com/ideaconnect/idct-sftp-client/commit/7a41b20b65eb1226f409735a67d07cf05b6b2775
https://github.com/ideaconnect/idct-sftp-client/commit/e0a3ea77ce383b56b69c7806324eb305e2553383

**Comment by ideaconnect** [comment]
Now resolved by `intval` on sftp resource.
