### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by jcrawford** [ideaconnect/idct-sftp-client#7]
Does this no longer work with PHP 7?  I upgraded from 5.6 not that long ago and this seemed to stop working.  This is a requirement for our app so having it down is not good for our application.

All I keep seeing in my terminal is this.

```
Warning: stat(): stat failed for ssh2.sftp://73/ItemAvailJSC.zip in /Users/jcrawford/TraderTools/vendor/idct/sftp-client/src/SftpClient.php on line 435
Failed to download ItemAvailJSC.zip... retrying in 5 seconds...
```

I can access the file and directory just fine using my normal SFTP Client (Transmit)

I am running PHP 7.0.15

**Comment by ideaconnect** [comment]
Hey!

It works normally with PHP 7.0 - the latest updates ensured that. Also it has a requirement for >= 5 so composer should not shout about any problems.

I just tested with one testing class:
```php
<?php

namespace Testing;

use IDCT\Networking\Ssh\SftpClient;
use IDCT\Networking\Ssh\Credentials;

class Test
{
    public function do()
    {
        $client = new SftpClient();
        $username = 'sftp-test';
        $password = 'sftp-pw';
        $host = 'idct.pl';

        $credentials = Credentials::withPassword($username, $password);

        $client->setCredentials($credentials);
        $client->connect($host);

        $client->download('/home/test/test.txt');
        $client->close();
    }
}
```

and executable:
```php
<?php
include "vendor/autoload.php";

$test = new Testing\Test();

$test->do();
```

One thing which changed in PHP 7.0 is absolute vs. relative path handling for SSH.SFTP.

Before if you tried to download let us say `ItemAvailJSC.zip` it tried to download it from the folder you are in by default when connecting. Now it always relates to root folder `/` therefore most likely it tries to download `/`. If you have the file in any specific subfolder - like `/opt/my-files/` be sure to set that in `->download(...)` -> therefore: `->download('/opt/my-files/ItemAvailJSC.zip')` or by setting the remote prefix:
```php
$sftpClient->download( $sftpClient->getRemotePrefix() . '/ItemAvailJSC.zip' );
```

*Why Remote Prefix is not applied automatically?*
As a convention I applied the prefixes here only for *saving* operations. Therefore when downloading `localPrefix` is in use and when uploading `remotePrefix`. I hope that makes sense. I am open here for any suggestions.
