### ISSUE TITLE
Sample running?

### ISSUE THREAD

**Issue by scascalesp** [ideaconnect/idct-sftp-client#8]
Hello
Can you put full sample working code? https://github.com/ideaconnect/idct-sftp-client/blob/master/tests/IntegrationTest.php use vendor/autoload.php

And 
use IDCT\Networking\Ssh\AuthMode;
use PHPUnit\Framework\TestCase;

I don't have them

**Comment by ideaconnect** [comment]
You have not executed `composer install` or not included the project in `composer.json` of a different (parent) project.

Now I have updated README.md file with usage details. It explains step by step usage. Also please get familiar with **composer** -> it really helps in management of libs in php projects.
